### ISSUE TITLE
KeyError for dynamic desk

### ISSUE THREAD

**Issue by yetty** [yetty/anki-unseen-and-buried-counts#4]
```
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt/webview.pyc", line 152, in _linkHandler
  File "aqt/toolbar.pyc", line 74, in _linkHandler
  File "aqt/toolbar.pyc", line 97, in _syncLinkHandler
  File "aqt/main.pyc", line 598, in onSync
  File "aqt/main.pyc", line 290, in loadCollection
  File "aqt/main.pyc", line 388, in moveToState
  File "aqt/main.pyc", line 392, in _deckBrowserState
  File "aqt/deckbrowser.pyc", line 27, in show
  File "aqt/deckbrowser.pyc", line 143, in _renderPage
  File "/Users/yetty/Library/Application Support/Anki2/addons/Unseen_and_buried_counts.py", line 57, in renderDeckTree
    node_rows = "".join([self._deckRow(node, depth, len(nodes)) for node in nodes])
  File "/Users/yetty/Library/Application Support/Anki2/addons/Unseen_and_buried_counts.py", line 78, in deckRow
    confId = str(deck["conf"])
KeyError: 'conf'
```

**Comment by Arthur-Milchior** [comment]
Already corrected. I didn't realize I never did a pull request for it.
The trouble being that, concerning filtered deck, the numbers are not defined.
